---
resources:
- name: api-build-scripts
  type: git
  source:
    uri: https://github.com/CliveCalmeyerTW/api-build-scripts.git
    branch: master
- name: address_book_go
  type: git
  source:
    uri: https://github.com/CliveCalmeyerTW/address_book_go.git
    branch: master
